global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - "/etc/prometheus/alert.rules.yml"
scrape_configs:
  - job_name: 'orchestrator'
    scrape_interval: 15s
    static_configs:
      - targets: ['host.docker.internal:9108']
    metrics_path: /metrics
    scheme: http
